/*
 * Copyright (c) 2026 wordgitet
 *
 * SPDX-License-Identifier: 0BSD
 */

import { describe, expect, test } from "bun:test";

import { run_editor_case } from "../support/editor_harness";

interface command_case {
	name: string;
	commands: readonly string[];
	stdout: string;
	initial?: readonly string[];
	input_kind?: "terminal" | "regular";
	status?: number;
}

const command_cases: readonly command_case[] = [
	{ name: "appends after the current line",
		commands: ["a", "four", ".", "1,$p"],
		stdout: "one\ntwo\nthree\nfour\n" },
	{ name: "appends after an addressed line",
		commands: ["1a", "middle", ".", "1,$p"],
		stdout: "one\nmiddle\ntwo\nthree\n" },
	{ name: "appends at address zero",
		commands: ["0a", "zero", ".", "1,$p"],
		stdout: "zero\none\ntwo\nthree\n" },
	{ name: "appends several lines in order",
		commands: ["2a", "alpha", "beta", ".", "1,$p"],
		stdout: "one\ntwo\nalpha\nbeta\nthree\n" },
	{ name: "accepts empty append input", commands: ["a", ".", ".="],
		stdout: "3\n" },
	{ name: "inserts before the current line",
		commands: ["i", "before", ".", "1,$p"],
		stdout: "one\ntwo\nbefore\nthree\n" },
	{ name: "inserts before the first line",
		commands: ["1i", "zero", ".", "1,$p"],
		stdout: "zero\none\ntwo\nthree\n" },
	{ name: "inserts before the final line",
		commands: ["$i", "before three", ".", "1,$p"],
		stdout: "one\ntwo\nbefore three\nthree\n" },
	{ name: "inserts several lines in order",
		commands: ["2i", "alpha", "beta", ".", "1,$p"],
		stdout: "one\nalpha\nbeta\ntwo\nthree\n" },
	{ name: "accepts empty insert input", commands: ["2i", ".", ".="],
		stdout: "2\n" },
	{ name: "changes the current line",
		commands: ["c", "THREE", ".", "1,$p"],
		stdout: "one\ntwo\nTHREE\n" },
	{ name: "changes the first line",
		commands: ["1c", "ONE", ".", "1,$p"],
		stdout: "ONE\ntwo\nthree\n" },
	{ name: "changes an addressed range",
		commands: ["1,2c", "replacement", ".", "1,$p"],
		stdout: "replacement\nthree\n" },
	{ name: "changes the complete buffer",
		commands: [",c", "new", "buffer", ".", "1,$p"],
		stdout: "new\nbuffer\n" },
	{ name: "changes a line to no lines",
		commands: ["2c", ".", "1,$p"], stdout: "one\nthree\n" },
	{ name: "deletes the current line", commands: ["d", "1,$p"],
		stdout: "one\ntwo\n" },
	{ name: "deletes the first line", commands: ["1d", "1,$p"],
		stdout: "two\nthree\n" },
	{ name: "deletes the final line", commands: ["$d", "1,$p"],
		stdout: "one\ntwo\n" },
	{ name: "deletes an addressed range", commands: ["1,2d", "1,$p"],
		stdout: "three\n" },
	{ name: "deletes the complete buffer", commands: [",d", ".="],
		stdout: "0\n" },
	{ name: "selects the following line after deletion",
		commands: ["2d", ".p"], stdout: "three\n" },
	{ name: "selects the new last line after final deletion",
		commands: ["$d", ".p"], stdout: "two\n" },
	{ name: "moves the first line after the last",
		commands: ["1m$", "1,$p"], stdout: "two\nthree\none\n" },
	{ name: "moves the last line before the first",
		commands: ["$m0", "1,$p"], stdout: "three\none\ntwo\n" },
	{ name: "moves a range after the last",
		commands: ["1,2m$", "1,$p"], stdout: "three\none\ntwo\n" },
	{ name: "moves a range before the first",
		commands: ["2,3m0", "1,$p"], stdout: "two\nthree\none\n" },
	{ name: "moves a line forward",
		commands: ["1m2", "1,$p"], stdout: "two\none\nthree\n" },
	{ name: "moves a line backward",
		commands: ["3m1", "1,$p"], stdout: "one\nthree\ntwo\n" },
	{ name: "rejects a move destination inside its range",
		commands: ["1,2m1"], stdout: "?\n", status: 1,
		input_kind: "terminal" },
	{ name: "copies the first line after the last",
		commands: ["1t$", "1,$p"], stdout: "one\ntwo\nthree\none\n" },
	{ name: "copies the last line before the first",
		commands: ["$t0", "1,$p"], stdout: "three\none\ntwo\nthree\n" },
	{ name: "copies an addressed range",
		commands: ["1,2t$", "1,$p"],
		stdout: "one\ntwo\nthree\none\ntwo\n" },
	{ name: "copies a line into the middle",
		commands: ["3t1", "1,$p"], stdout: "one\nthree\ntwo\nthree\n" },
	{ name: "keeps a mark on a moved line",
		commands: ["1ka", "1m$", "'ap"], stdout: "one\n" },
	{ name: "keeps a mark on the original copied line",
		commands: ["1ka", "1t$", "'a="], stdout: "1\n" },
	{ name: "joins the default pair", initial: ["one", "two", "three", "four"],
		commands: ["2p", "j", "1,$p"],
		stdout: "two\none\ntwothree\nfour\n" },
	{ name: "joins two addressed lines", commands: ["1,2j", "1,$p"],
		stdout: "onetwo\nthree\n" },
	{ name: "joins three addressed lines", commands: ["1,3j", "1,$p"],
		stdout: "onetwothree\n" },
	{ name: "accepts a single-line join", commands: ["2,2j", "1,$p"],
		stdout: "one\ntwo\nthree\n" },
	{ name: "undoes append", commands: ["a", "four", ".", "u", "1,$p"],
		stdout: "one\ntwo\nthree\n" },
	{ name: "undoes insert", commands: ["1i", "zero", ".", "u", "1,$p"],
		stdout: "one\ntwo\nthree\n" },
	{ name: "undoes change", commands: ["2c", "TWO", ".", "u", "1,$p"],
		stdout: "one\ntwo\nthree\n" },
	{ name: "undoes delete", commands: ["2d", "u", "1,$p"],
		stdout: "one\ntwo\nthree\n" },
	{ name: "undoes move", commands: ["1m$", "u", "1,$p"],
		stdout: "one\ntwo\nthree\n" },
	{ name: "undoes copy", commands: ["1t$", "u", "1,$p"],
		stdout: "one\ntwo\nthree\n" },
	{ name: "undoes join", commands: ["1,2j", "u", "1,$p"],
		stdout: "one\ntwo\nthree\n" },
	{ name: "toggles the last change with repeated undo",
		commands: ["2d", "u", "u", "1,$p"], stdout: "one\nthree\n" },
	{ name: "preserves a mark on the first replacement line",
		commands: ["2ka", "2c", "TWO", ".", "'ap"], stdout: "TWO\n" },
	{ name: "removes a mark with its deleted line",
		commands: ["2ka", "2d", "'ap"], stdout: "?\n", status: 1,
		input_kind: "terminal" },
	{ name: "prints the current line", commands: ["p"], stdout: "three\n" },
	{ name: "prints the current line with its number", commands: ["n"],
		stdout: "3\tthree\n" },
	{ name: "prints the current line visibly", commands: ["l"],
		stdout: "three$\n" },
	{ name: "prints a plain range", commands: ["1,2p"],
		stdout: "one\ntwo\n" },
	{ name: "prints a numbered range", commands: ["1,2n"],
		stdout: "1\tone\n2\ttwo\n" },
	{ name: "prints a visible range", commands: ["1,2l"],
		stdout: "one$\ntwo$\n" },
	{ name: "escapes tabs in visible output", initial: ["a\tb"],
		commands: ["l"], stdout: "a\\tb$\n" },
	{ name: "escapes backslashes in visible output", initial: ["a\\b"],
		commands: ["l"], stdout: "a\\\\b$\n" },
	{ name: "prints after delete with a p suffix", commands: ["1dp"],
		stdout: "two\n" },
	{ name: "numbers after delete with an n suffix", commands: ["1dn"],
		stdout: "1\ttwo\n" },
	{ name: "lists after delete with an l suffix", commands: ["1dl"],
		stdout: "two$\n" },
	{ name: "prints after append with a p suffix",
		commands: ["ap", "four", "."], stdout: "four\n" },
	{ name: "numbers after change with an n suffix",
		commands: ["2cn", "TWO", "."], stdout: "2\tTWO\n" },
	{ name: "lists after move with an l suffix", commands: ["1m$l"],
		stdout: "one$\n" },
	{ name: "prints after the equals command suffix", commands: ["=p"],
		stdout: "3\nthree\n" },
	{ name: "accepts help with no previous error", commands: ["h"],
		stdout: "" },
	{ name: "reports detailed errors while help mode is enabled",
		commands: ["H", "/missing/p"],
		stdout: "?\nregular expression not found\n", status: 1,
		input_kind: "terminal" },
	{ name: "reports the previous error with help",
		commands: ["/missing/p", "h"],
		stdout: "?\nregular expression not found\n", status: 1,
		input_kind: "terminal" },
	{ name: "rejects an unknown command", commands: ["x"],
		stdout: "?\n", status: 1, input_kind: "terminal" },
	{ name: "rejects undo without a prior change", initial: [],
		commands: ["u"], stdout: "?\n", status: 1,
		input_kind: "terminal" },
	{ name: "rejects a long mark name", commands: ["1kab"],
		stdout: "?\n", status: 1, input_kind: "terminal" },
	{ name: "rejects an uppercase mark name", commands: ["1kA"],
		stdout: "?\n", status: 1, input_kind: "terminal" },
	{ name: "rejects filename output without a remembered pathname",
		initial: [], commands: ["f"], stdout: "?\n", status: 1,
		input_kind: "terminal" },
	{ name: "rejects an invalid move destination", commands: ["1mword"],
		stdout: "?\n", status: 1, input_kind: "terminal" },
	{ name: "rejects print on an empty buffer", initial: [], commands: ["p"],
		stdout: "?\n", status: 1, input_kind: "terminal" },
	{ name: "appends to an empty buffer", initial: [],
		commands: ["a", "first", ".", "p"], stdout: "first\n" },
	{ name: "allows a warned quit after a non-mutating command",
		commands: ["q", "p", "q", "q"], stdout: "?\nthree\n" },
];

describe("editor command regressions", () => {
	for (const item of command_cases) {
		test(item.name, async () => {
			const initial = item.initial ?? ["one", "two", "three"];
			const setup = initial.length === 0
				? []
				: ["a", ...initial, "."];
			const result = await run_editor_case({
				lines: [...setup, ...item.commands, "Q"],
				input_kind: item.input_kind ?? "regular",
			});
			expect(result.status).toBe(item.status ?? 0);
			expect(result.stdout).toBe(item.stdout);
			expect(result.stderr).toBe("");
		});
	}
});
