/*
 * Copyright (c) 2026 wordgitet
 *
 * SPDX-License-Identifier: 0BSD
 */

import { describe, expect, test } from "bun:test";

import { run_editor_case } from "../support/editor_harness";

interface global_case {
	name: string;
	initial: readonly string[];
	commands: readonly string[];
	stdout: string;
	input_kind?: "regular" | "terminal";
	status?: number;
}

const global_cases: readonly global_case[] = [
	{ name: "defaults global to print", initial: ["alpha", "beta", "alpha"],
		commands: ["g/alpha"], stdout: "alpha\nalpha\n" },
	{ name: "defaults inverse global to print",
		initial: ["alpha", "beta", "alpha"], commands: ["v/alpha"],
		stdout: "beta\n" },
	{ name: "prints global matches", initial: ["ax", "by", "az"],
		commands: ["g/^a/p"], stdout: "ax\naz\n" },
	{ name: "prints inverse-global matches", initial: ["ax", "by", "az"],
		commands: ["v/^a/p"], stdout: "by\n" },
	{ name: "limits global to an addressed range",
		initial: ["x1", "x2", "x3", "x4"], commands: ["2,3g/x/p"],
		stdout: "x2\nx3\n" },
	{ name: "limits inverse global to an addressed range",
		initial: ["x1", "other", "x3", "other"],
		commands: ["2,3v/x/p"], stdout: "other\n" },
	{ name: "accepts an alternate global delimiter",
		initial: ["alpha", "beta"], commands: ["g#alpha#p"],
		stdout: "alpha\n" },
	{ name: "accepts an alternate inverse delimiter",
		initial: ["alpha", "beta"], commands: ["v#alpha#p"],
		stdout: "beta\n" },
	{ name: "reuses the previous global expression",
		initial: ["alpha", "beta", "alpha"],
		commands: ["/alpha/p", "g//p"],
		stdout: "alpha\nalpha\nalpha\n" },
	{ name: "deletes every global match", initial: ["x1", "keep", "x2"],
		commands: ["g/x/d", "1,$p"], stdout: "keep\n" },
	{ name: "deletes every inverse match", initial: ["x1", "keep", "x2"],
		commands: ["v/x/d", "1,$p"], stdout: "x1\nx2\n" },
	{ name: "substitutes every global match",
		initial: ["cat", "dog", "cat"],
		commands: ["g/cat/s/cat/CAT/", "1,$p"],
		stdout: "CAT\ndog\nCAT\n" },
	{ name: "substitutes every inverse match",
		initial: ["cat", "dog", "cat"],
		commands: ["v/cat/s/dog/DOG/", "1,$p"],
		stdout: "cat\nDOG\ncat\n" },
	{ name: "appends after every global match",
		initial: ["x1", "keep", "x2"],
		commands: ["g/x/a\\", "added", "1,$p"],
		stdout: "x1\nadded\nkeep\nx2\nadded\n" },
	{ name: "inserts before every global match",
		initial: ["x1", "keep", "x2"],
		commands: ["g/x/i\\", "before", "1,$p"],
		stdout: "before\nx1\nkeep\nbefore\nx2\n" },
	{ name: "changes every global match",
		initial: ["x1", "keep", "x2"],
		commands: ["g/x/c\\", "changed", "1,$p"],
		stdout: "changed\nkeep\nchanged\n" },
	{ name: "changes every inverse match",
		initial: ["x1", "keep", "x2"],
		commands: ["v/x/c\\", "changed", "1,$p"],
		stdout: "x1\nchanged\nx2\n" },
	{ name: "executes a multiline global list",
		initial: ["alpha", "beta", "alpha"],
		commands: [
			"g/alpha/a\\", "alpha marked\\", ".\\", "s/alpha/ALPHA/",
			"1,$p",
		],
		stdout: "alpha\nALPHA marked\nbeta\nalpha\nALPHA marked\n" },
	{ name: "accepts an omitted input terminator in a global list",
		initial: ["alpha", "beta", "alpha"],
		commands: ["g/alpha/c\\", "replacement", "1,$p"],
		stdout: "replacement\nbeta\nreplacement\n" },
	{ name: "accepts an omitted inverse input terminator",
		initial: ["alpha", "beta", "alpha"],
		commands: ["v/alpha/c\\", "replacement", "1,$p"],
		stdout: "alpha\nreplacement\nalpha\n" },
	{ name: "leaves current unchanged when global finds no match",
		initial: ["one", "two", "three"],
		commands: ["g/missing/p", ".="], stdout: "3\n" },
	{ name: "sets current to the final global match",
		initial: ["x1", "keep", "x2"], commands: ["g/x/p", ".="],
		stdout: "x1\nx2\n3\n" },
	{ name: "sets current to the final inverse match",
		initial: ["x1", "keep", "x2"], commands: ["v/x/p", ".="],
		stdout: "keep\n2\n" },
	{ name: "undoes a complete global deletion",
		initial: ["x1", "keep", "x2"],
		commands: ["g/x/d", "u", "1,$p"], stdout: "x1\nkeep\nx2\n" },
	{ name: "undoes a complete inverse deletion",
		initial: ["x1", "keep", "x2"],
		commands: ["v/x/d", "u", "1,$p"], stdout: "x1\nkeep\nx2\n" },
	{ name: "accepts undo after a no-match global",
		initial: ["one", "two"], commands: ["g/missing/d", "u", "1,$p"],
		stdout: "one\ntwo\n" },
	{ name: "does not undo through a no-change global",
		initial: ["one", "two"],
		commands: ["1s/one/ONE/", "g/missing/d", "u", "1,$p"],
		stdout: "ONE\ntwo\n" },
	{ name: "marks each match and retains the final mark",
		initial: ["x1", "keep", "x2"], commands: ["g/x/ka", "'ap"],
		stdout: "x2\n" },
	{ name: "copies every selected line",
		initial: ["x1", "keep", "x2"],
		commands: ["g/x/t$", "1,$p"],
		stdout: "x1\nkeep\nx2\nx1\nx2\n" },
	{ name: "removes every selected line", initial: ["x1", "x2"],
		commands: ["g/x/d", ".="], stdout: "0\n" },
	{ name: "interactive global writes each match",
		initial: ["x1", "keep", "x2"], commands: ["G/x/", "", ""],
		stdout: "x1\nx2\n", input_kind: "terminal" },
	{ name: "interactive inverse writes each non-match",
		initial: ["x1", "keep", "x2"], commands: ["V/x/", ""],
		stdout: "keep\n", input_kind: "terminal" },
	{ name: "interactive global executes print",
		initial: ["x1", "keep", "x2"], commands: ["G/x/", "p", "p"],
		stdout: "x1\nx1\nx2\nx2\n", input_kind: "terminal" },
	{ name: "interactive inverse executes print",
		initial: ["x1", "keep", "x2"], commands: ["V/x/", "p"],
		stdout: "keep\nkeep\n", input_kind: "terminal" },
	{ name: "interactive global repeats ampersand commands",
		initial: ["x1", "keep", "x2"],
		commands: ["G/x/", "s/x/X/", "&", "1,$p"],
		stdout: "x1\nx2\nX1\nkeep\nX2\n", input_kind: "terminal" },
	{ name: "interactive inverse repeats ampersand commands",
		initial: ["x", "one", "two"],
		commands: ["V/x/", "s/o/O/", "&", "1,$p"],
		stdout: "one\ntwo\nx\nOne\ntwO\n", input_kind: "terminal" },
	{ name: "interactive global stops after command failure",
		initial: ["x1", "x2"],
		commands: ["G/x/", "s/missing/value/", ".="],
		stdout: "x1\n1\n", input_kind: "terminal" },
	{ name: "interactive global stops after unconditional quit",
		initial: ["one", "two"], commands: ["G/o/", "Q"],
		stdout: "one\n", input_kind: "terminal" },
	{ name: "interactive global unmarks replaced future lines",
		initial: ["x1", "x2", "x3", "x4"],
		commands: ["1,3G/x/", ".+1s/$/ changed/", ".+1s/$/ changed/",
			"1,$p"],
		stdout: "x1\nx3\nx1\nx2 changed\nx3\nx4 changed\n",
		input_kind: "terminal" },
	{ name: "interactive inverse unmarks replaced future lines",
		initial: ["one", "two", "three", "four"],
		commands: ["1,3V/z/", ".+1s/$/ changed/", ".+1s/$/ changed/",
			"1,$p"],
		stdout: "one\nthree\none\ntwo changed\nthree\nfour changed\n",
		input_kind: "terminal" },
	{ name: "applies list suffix to interactive global",
		initial: ["alpha", "beta"], commands: ["G/alpha/l", "p"],
		stdout: "alpha\nalpha\nalpha$\n", input_kind: "terminal" },
	{ name: "limits interactive global by address",
		initial: ["x1", "x2", "x3"], commands: ["2,3G/x/", "", ""],
		stdout: "x2\nx3\n", input_kind: "terminal" },
	{ name: "leaves current unchanged after interactive no-match",
		initial: ["one", "two"], commands: ["G/missing/", ".="],
		stdout: "2\n", input_kind: "terminal" },
	{ name: "rejects a blank global delimiter", initial: ["one"],
		commands: ["g one"], stdout: "?\n", status: 1,
		input_kind: "terminal" },
	{ name: "stops a noninteractive global after a failed command",
		initial: ["x1", "x2"], commands: ["g/x/s/missing/value/"],
		stdout: "?\n", status: 1, input_kind: "terminal" },
];

describe("global command regressions", () => {
	for (const item of global_cases) {
		test(item.name, async () => {
			const result = await run_editor_case({
				lines: ["a", ...item.initial, ".", ...item.commands, "Q"],
				input_kind: item.input_kind ?? "regular",
			});
			expect(result.status).toBe(item.status ?? 0);
			expect(result.stdout).toBe(item.stdout);
			expect(result.stderr).toBe("");
		});
	}
});
